### ISSUE TITLE
.md files

### ISSUE THREAD

**Issue by FrizzaUK** [nevir/groc#112]
Is it possible for readme files and other .md files to utilize the whole screen rather than just the comment block on the left?  It would be nice if the code block could be removed or conditioned in some way.

**Comment by sjorek** [comment]
… the same principle should apply to the previously introduced ( https://github.com/nevir/groc/pull/109 ) `codeOnly` - feature, where we have only rendered code. I'll look what I can do, as I miss it too …

**Comment by sjorek** [comment]
… and if _one is_ (= _I'm_) going to implement it, please take this issue into account: https://github.com/nevir/groc/issues/114

**Comment by sjorek** [comment]
Not exactly what was requested, but this branch https://github.com/sjorek/groc/tree/feature-collapsible-columns offers (to my mind) a quite appealing solution to this problem. A rendered result can be viewed here: http://sjorek.github.io/groc/ … open this in browser und click the last tiny icon in the toolbar (top-right).

**Comment by FrizzaUK** [comment]
I think it looks great - love the idea that it can display the comments on the left or inline.  I will install that version and see how I get on.  Many thanks for your help (and work) :)

**Comment by sjorek** [comment]
… you're welcome. The inline idea isn't mine ! If you narrow the browsers window in the 2-column view (or use a small screen like on an iPhone) you'll see it has already been there … 

Actually there was no need to close this issue, as nothing has been merged into the master's HEAD yet …
