### ISSUE TITLE
Is there documentation on formatting and supported Markdown syntax?

### ISSUE THREAD

**Issue by bclinkinbeard** [nevir/groc#133]
Just trying to figure out what is and isn't supported. The following renders as expected except the list.

```
/*
# Watchers
This **could** be *interesting*, but we'll have to see.
Maybe we can do lists?
* One
* Two
* Three
*/
```

**Comment by sjorek** [comment]
Groc renders markdown using the https://github.com/coreyti/showdown package.

**Comment by bclinkinbeard** [comment]
Shouldn't the list above be working then? What am I missing?

**Comment by sjorek** [comment]
Which language are you using ?

Javascript knows:

```
/**
 * Comment
 * @doctag
 */
```

… hence we usually strip the first `'*'`` from every comment-line. You should read https://github.com/nevir/groc/blob/master/lib/languages.coffee#L46 …

**Comment by bclinkinbeard** [comment]
OK, I didn't realize Groc expects the JSDoc format delimiters. Is that documented somewhere? Using the delimiters does work, but only if I remove the JSDoc annotations for params, return val and @private. The following comment block.

```
/**
 * Ummm, OK.
 * 
 * @param $scope
 */
```

Results in the following error.

```
Generating documentation...
‡ Processing /Users/bclinkinbeard/SpatialKey/SKESD/src/modules/podContents/PodContentsController.js
‡ Split /Users/bclinkinbeard/SpatialKey/SKESD/src/modules/podContents/PodContentsController.js into 27 segments
! Failed to parse doc tags /Users/bclinkinbeard/SpatialKey/SKESD/src/modules/podContents/PodContentsController.js: Cannot read property '1' of null
   TypeError: Cannot read property '1' of null
      at Object.module.exports.DOC_TAGS.param.parseValue (/usr/local/lib/node_modules/groc/lib/doc_tags.coffee:122:31)
      at Object.module.exports.Utils.parseDocTags (/usr/local/lib/node_modules/groc/lib/utils.coffee:472:41)
      at Default.module.exports.Base.renderFile (/usr/local/lib/node_modules/groc/lib/styles/base.coffee:31:20)
      at /usr/local/lib/node_modules/groc/lib/project.coffee:74:24
      at fs.js:266:14
      at Object.oncomplete (fs.js:107:15)
```

I'm really not trying to be a pain, I just want to understand how I can and cannot use this tool because it seems really close to exactly what I need, but I obviously have to work out these kinks before fully adopting it.

**Comment by sjorek** [comment]
Groc does not **expect** JSdoc-tags, it just supports some of them. So, that your comment fails, is a known bug, your comment should either read:

```
/**
 * Ummm, OK.
 * 
 * @param {ClassOrType} $scope The description …
 */
```

… or just (as a suggestion):

```
 /*
 Ummm, OK.

 Parameters:
 - *$scope*: The description …
 - *$anotherOne*: Another description …
 */
```

**Comment by sjorek** [comment]
Regarding your question:

> OK, I didn't realize Groc expects the JSDoc format delimiters. Is that documented somewhere? 

Use the force and read the source: https://github.com/nevir/groc/blob/master/lib/doc_tags.coffee

**Comment by bclinkinbeard** [comment]
Yes, because every person wanting to use the library reading the full source is much easier than adding a few sentences of documentation or examples.

**Comment by joseph-jja** [comment]
I'm getting this error, and wondering why?  --force doesn't really help when it still fails.  Is this supposed to mean something?  

TypeError: Cannot read property '1' of null

**Comment by mryellow** [comment]
>  Is this supposed to mean something? 

+1

Following the documentation, getting it running, then being presented with this error on first run is not very welcoming.

So it is saying that it doesn't like a comment somewhere?

**Comment by borisdiakur** [comment]
+1
A stacktrace pointing to the location with the unsupported tag or whatever would rock!
