### ISSUE TITLE
Latest Jade Version `doctype` warning

### ISSUE THREAD

**Issue by evanshajed** [nevir/groc#152]
`!!!` is deprecated in latest **`Jade v1.0.2`** updated a day earlier. I'm using **[grunt-groc](https://github.com/jdcataldo/grunt-groc)** to generate my documentation which was working fine with the previous release `v0.35.0`. Can you please suggest me any quick fix which I may adopt in one of my project _[Front-End-Workflow](https://github.com/themestent/front-end-workflow)_ so that it only uses **Jade ~v0.35.0**

**Comment by kmdavis** [comment]
#151 fixes this

**Comment by evanshajed** [comment]
I checked that issue while finding a solution but it still downloads the latest version. You can check it from my given project repo link.

**Comment by evanshajed** [comment]
Fixes were not merged with master tree. Can we have a quick update please?

**Comment by dariusk** [comment]
Version of groc on npm is still broken, someone ought to update.
