### ISSUE TITLE
Support block comments

### ISSUE THREAD

**Issue by Raynos** [nevir/groc#16]
Depending on how much my hatred of coffeescript gets in the way I may make a pull request for this.

**Comment by nevir** [comment]
Heh, it would be much appreciated!  

Things to keep in mind if you do muck around in that code:
- I want to refactor the hell out [`utils.splitSource`](https://github.com/nevir/groc/blob/master/lib/utils.coffee#L73), you're welcome to tear it apart if it makes things easier.
  - My initial thinking is that there might need to be multiple (generic) line matching funcs that can be configured
  - Eventually, I want to support literate haskell, coffeescript and any other language that explicitly supports that style (i.e. comments aren't prefixed by anything, and code is indented/delimited by something like `>`)

**Comment by Raynos** [comment]
I was just going to ask for this feature again but I forgot I asked for it before o/ 

Turns out my hatred of coffeescript got in the way ._.

**Comment by nevir** [comment]
Heh, that's alright.  I definitely want to support them, though priority-wise it's a bit lower on my list (I want to make this a good alternative to docco before I start expanding it feature-wise past that)

**Comment by emilecantin** [comment]
It gets in the way of adding CSS / LESS support, see #35

**Comment by jaredly** [comment]
+1 yes please!!

**Comment by kmdavis** [comment]
This pull request adds support for block comments (including single line block comments) https://github.com/nevir/groc/pull/83

**Comment by kmdavis** [comment]
closed by pull request #83
