### ISSUE TITLE
Trouble running after installing

### ISSUE THREAD

**Issue by sndrs** [nevir/groc#18]
Hi there,

I'm new to using node.js so apologies if this is just my ignorance and not a bug...

But having installed croc (which looks amazing btw! - i really want to run it :), i cannot get it to run. 

node and pigments are installed (used docco fine), but running croc, it either fails silently or throws the following error:

```
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object function glob(pattern, options, cb) {
  if (typeof options === "function") cb = options, options = {}
  if (!options) options = {}

  if (typeof options === "number") {
    deprecated()
    return
  }

  var m = new Glob(pattern, options, cb)

  if (options.sync) {
    return m.found
  } else {
    return m
  }
} has no method 'globSync'
    at Object.CLI (/usr/local/lib/node_modules/groc/lib/cli.coffee:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/groc/bin/groc:3:17)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:470:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

had a good google and can't find anything related to that error.

I have stub README.md and almost empty .groc.json:

```
{
  "globs": ["./*.js"]
}
```

look in anyway familiar?

**Comment by sndrs** [comment]
Node is v0.6.7 btw, running on lion.

**Comment by nevir** [comment]
Hmm, your setup looks good - the globbing library I use might have changed its API out from under me from the looks of it.  I'll take a look, and thanks for giving this a whirl :)

**Comment by nevir** [comment]
Yup, [node-glob](https://github.com/isaacs/node-glob) was updated - I've pushed out groc v0.2.7 that takes advantage of it, and has more restrictive dependency versioning.  This should do the trick for ya!

**Comment by sndrs** [comment]
that's done it - perfect! 

thank you :)
