### ISSUE TITLE
--silent option

### ISSUE THREAD

**Issue by unindented** [nevir/groc#20]
I'm integrating `groc` in my `Makefile`, and even the default output is too verbose, so I'm missing a `--silent` option.

If you think it could be useful, I could take a stab at it.

However, I don't know if it should set the trace level to `WARN` or `ERROR`. What do you think?

**Comment by nevir** [comment]
Hmm.  Go with `ERROR` - since it's an explicit option.  (The only main thing that groc warns about right now is when you glob files in unsupported formats)

I think it's useful :)

**Comment by nevir** [comment]
Solved via #21
