### ISSUE TITLE
Github flavoured markdown

### ISSUE THREAD

**Issue by timmak** [nevir/groc#25]
Should it not support github  or other flavours of markdown?

**Comment by nevir** [comment]
The problem with [GFM](http://github.github.com/github-flavored-markdown/) is that one of its main features is to respect newlines.  This completely destroys the layout of the left column

I'd love to support all the other github-specific behaviors, though.  I wasn't able to find a library that managed this, though (docco forked showdown to deal w/ issues like that - which I'd like to avoid if possible)

**Comment by timmak** [comment]
If I can get a chance I will have a look at it and see if I can do anything

**Comment by dignifiedquire** [comment]
Why not switch to [marked](https://github.com/chjj/marked)?

**Comment by killercup** [comment]
Switch to marked: #150
