### ISSUE TITLE
Argument descriptions

### ISSUE THREAD

**Issue by nevir** [nevir/groc#28]
A convention for describing function arguments and their constraints would be super useful.  Similar to javadoc/etc, but not as heavy?

**Comment by kmdavis** [comment]
My latest commit on Gilt's fork adds support for javadoc/jsdoc

https://github.com/gilt/groc/commit/21d50e34e5b12b435dbd35ff1401dd050f26b8d0

Once pull request #83 get's merged, I can create a pull request for this.

**Comment by kmdavis** [comment]
closed by pull request #83

**Comment by kmdavis** [comment]
closed this too soon, sorry
