### ISSUE TITLE
Emphasis not working?

### ISSUE THREAD

**Issue by donnguyen-dev** [nevir/groc#32]
For example in the following JavaScript snippet

  // Useful when interfacing with server-side languages like **PHP** that make

PHP does not appear in bold

**Comment by nevir** [comment]
Curses!  Blatant oversight, I'll get this in the next release :(

**Comment by realyze** [comment]
Would be great if this worked. 
Still - a really nice piece of SW, good job, @nevir!

**Comment by nevir** [comment]
Terrible terrible oversight ><  Fixed in `v0.4.0`
