### ISSUE TITLE
Support for LESS

### ISSUE THREAD

**Issue by emilecantin** [nevir/groc#35]
I just tried adding LESS support in languages.coffee, using the CSS lexer (there's no LESS lexer), but I found an issue: CSS doesn't officially have single-line comments, so pygments doesn't work on them: http://pygments.org/demo/45468/. This makes Groc fail, because it can't find its segments separators in the highlighted code.

Is there a way to add block-comments support to groc?

LESS does have single-line comments(http://lesscss.org/#-comments), so I submitted a feature request to pygments to add a LESS lexer: https://bitbucket.org/birkenfeld/pygments-main/issue/780/add-a-less-lexer

**Comment by jaredly** [comment]
Pygments has a lexer for Scss - does that work?

**Comment by kmdavis** [comment]
Both the scss and sass lexers work, but the sass lexer works better

I have a commit on Gilt's fork, but it depends on pull request #83 to add support for block comments

https://github.com/gilt/groc/commit/02158b600d2f4354d9cdda5638bfadca2b4e5aff
