### ISSUE TITLE
`npm install -g groc` fails

### ISSUE THREAD

**Issue by ghost** [nevir/groc#40]
It appears to be having issues installing the "autorequire" node package from the npmjs repository.

Error: No compatible version found: autorequire@'>=0.3.0- <0.4.0-'

**Comment by emilecantin** [comment]
Are you using node.js 0.8.0 ? See: https://github.com/nevir/node-autorequire/issues/3

**Comment by CoffeeAndCode** [comment]
Indeed I was.  Thanks.

**Comment by nevir** [comment]
I fixed the related issue on `autorequire`, but I still have some compatibility issues to work through with groc.  I've got a [branch in progress](https://github.com/nevir/groc/tree/0.8-compat).  For now we're stuck on 0.4-0.6

**Comment by CoffeeAndCode** [comment]
Thanks @nevir

**Comment by sonnym** [comment]
@CoffeeAndCode you may want to check out my fork of groc, which is working with node v0.8.2 ( https://github.com/sonnym/groc/tree/0.8-compat ).  I just opened a pull request last night, so it may be some time before it lands upstream.

**Comment by CoffeeAndCode** [comment]
Thanks for the update @sonnym

**Comment by evanmoran** [comment]
This worked for me on node v0.8.6
