### ISSUE TITLE
Sprocket style require's on express show on documentation.

### ISSUE THREAD

**Issue by reaktivo** [nevir/groc#57]
I'm using the Snockets module to handle js concatenation and it uses the following to indicate a dependency in coffeescript files.
# = require dependency

Is there a way to mark the code so it doesn't put it on the documentation side?

**Comment by nevir** [comment]
Yeah, annoying!  I've just pushed groc 0.3.0 that "fixes" this by enforcing that comments have a space after the `#` (or other) token to be considered a comment.

It's unfortunately a sledgehammer approach (I'd much rather have a sane default per language/project type, but that's much larger of a change).  This seems like the proper default behavior
