### ISSUE TITLE
No index produced

### ISSUE THREAD

**Issue by semperos** [nevir/groc#62]
I'm a new user to groc, here is my setup:
- Mac OSX Mountain Lion (10.8.2)
- groc 0.3.0
- pygmentize 1.4
- node 0.8.7
- npm 1.1.49

I have a `README.md` file in the same directory where I run `groc`, but the generated `doc/` folder does not have any index file, nor do I see the README content anywhere. This results in separate HTML files with no clear entry point. What is the intended behavior when a README file is present? Does it produce a `index.html` file in the root of the generated documentation directory?

Here's how I'm calling `groc`:

```
groc -e "node_modules/**" --no-whitespace-after-token -i ./README.md "**/*.coffee"
```

Even with the explicit `-i` option, it still doesn't seem to pickup the README file. Am I missing something?

**Comment by ostronom** [comment]
Was there any progress fixing this issue?

**Comment by sjorek** [comment]
1. I don't have this problem under OS.X 10.9 and Ubuntu 13.10. Can you give more infos, that could help to reproduce your problem ?
2. What happens if you run `groc` on its own source folder - does it produce the desired result in `./doc/` ?
3. Can you provide `--verbose` output ?

**Comment by ostronom** [comment]
Now i understand, that README.md is processed to /doc/index.html. I thought that it will be autogenerated (like in sphinx and others). I think, that it should be documented somewhere..

**Comment by sjorek** [comment]
… create a patch and provide a pull-request to the README.md, if you think thats really needed. But actually you could easily recognize this, when you read groc's documentation = groc's source code … but I don't want to offend you, with my opinion. I just wanted to give some help …

cheers,
:innocent:

**Comment by semperos** [comment]
Haven't touched or looked at this in a long time, closing.
