### ISSUE TITLE
whitespace-after-token default value is limiting

### ISSUE THREAD

**Issue by ghost** [nevir/groc#74]
I ran groc several times and it was not picking up comments in my javascript files.  I finally resorted to `whitespace-after-token: false` in my `.groc.json` and it worked.  Why is `whitespace-after-token` set to true as the default value?  It seems really limiting to those who may or may not use spaces after `//` tokens.

**Comment by jdcataldo** [comment]
Just submitted a pull request for this: https://github.com/nevir/groc/pull/75

**Comment by kmdavis** [comment]
this was merged 5 months ago.  closing
