### ISSUE TITLE
Syntax highlighting in comments

### ISSUE THREAD

**Issue by achingbrain** [nevir/groc#94]
Sometimes it's useful to put code examples inside backticks in comments and readme files.

These appear to get parsed into code blocks correctly but then don't get any syntax highlighting.

Any chance of adding this?

**Comment by sjorek** [comment]
… hmmm interesting idea :+1: 

Just some thoughts:
- As far as I get it the [showdown](https://npmjs.org/package/showdown) package creates these code blocks,
  hence it's not _groc_'s task
  - Alternative (a): A solution could be implemented as showdown-extension provided by _groc_
  - Alternative (b): A solution could be implemented as separate node-package providing a showdown-extension
    which (re-)uses _groc_'s pygmentize implementation
- The solution could incorporate [github's syntax-highlighting
  conventions](https://help.github.com/articles/github-flavored-markdown#syntax-highlighting)
- Why don't you start right off and let me join your attempt ? :smirk: 

Cheers,
Stephan

**Comment by killercup** [comment]
#150 has this! (See [my fork's documentation](http://killercup.github.io/groc/))

**Comment by achingbrain** [comment]
That looks awesome, nice work.  Hopefully someone will merge it.
